mytestkey=This value is from LOCAL properties file

paypal.client.id=Ac-9ndOw4Kw0CP71y1-quVrDmLBX0744bEP8Vk9ZHlPzQlDftpniRhQ6GrY6guY5wMkV3uWfoce662gm
paypal.client.secret=EDwpPybjN3zA8RZKR9SoeYAUUkWpBhHR9zzc94abYDzmoMUxMVEU7ZyKiL632dqx4-7tqOCZVfgVoHVE

paypal.oauth.url=https://api-m.sandbox.paypal.com/v1/oauth2/token